# Generated by Django 3.1.6 on 2021-07-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0004_auto_20210720_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='addressfull',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='zestimate',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
