# Generated by Django 3.1.6 on 2021-07-22 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blakerussell', '0006_auto_20210722_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=200)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(choices=[('Year Built', 'Year Built'), ('Home Size', 'Home Size'), ('Lot Size', 'Lot Size'), ('Bedrooms', 'Bedrooms'), ('Bathrooms', 'Bathrooms'), ('Zestimate', 'Zestimate')], max_length=50)),
                ('apieendpointaddon', models.CharField(blank=True, max_length=200)),
                ('apiendpointcustom', models.CharField(blank=True, max_length=200)),
                ('apikeylocation', models.CharField(choices=[('Header', 'Header'), ('Params', 'Params')], max_length=50)),
                ('apikeylocationkey', models.CharField(blank=True, max_length=200)),
                ('header1key', models.CharField(blank=True, max_length=200)),
                ('header1value', models.CharField(blank=True, max_length=200)),
                ('header2key', models.CharField(blank=True, max_length=200)),
                ('header2value', models.CharField(blank=True, max_length=200)),
                ('params1key', models.CharField(blank=True, max_length=200)),
                ('params1value', models.CharField(blank=True, max_length=200)),
                ('params2key', models.CharField(blank=True, max_length=200)),
                ('params2value', models.CharField(blank=True, max_length=200)),
                ('params3key', models.CharField(blank=True, max_length=200)),
                ('params3value', models.CharField(blank=True, max_length=200)),
                ('params4key', models.CharField(blank=True, max_length=200)),
                ('params4value', models.CharField(blank=True, max_length=200)),
                ('params5key', models.CharField(blank=True, max_length=200)),
                ('params5value', models.CharField(blank=True, max_length=200)),
                ('params6key', models.CharField(blank=True, max_length=200)),
                ('params6value', models.CharField(blank=True, max_length=200)),
                ('params7key', models.CharField(blank=True, max_length=200)),
                ('params7value', models.CharField(blank=True, max_length=200)),
                ('params8key', models.CharField(blank=True, max_length=200)),
                ('params8value', models.CharField(blank=True, max_length=200)),
                ('params9key', models.CharField(blank=True, max_length=200)),
                ('params9value', models.CharField(blank=True, max_length=200)),
                ('params10key', models.CharField(blank=True, max_length=200)),
                ('params10value', models.CharField(blank=True, max_length=200)),
                ('apiendpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apiendpoint', to='blakerussell.apistore')),
            ],
            options={
                'ordering': ['datapoint'],
            },
        ),
    ]
