# Generated by Django 3.1.6 on 2021-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0007_auto_20210722_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicall',
            name='apikeylocation',
        ),
        migrations.RemoveField(
            model_name='apicall',
            name='apikeylocationkey',
        ),
        migrations.AddField(
            model_name='apistore',
            name='apikeylocation',
            field=models.CharField(choices=[('Header', 'Header'), ('Params', 'Params')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apistore',
            name='keyname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='apieendpointaddon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='apiendpointcustom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='header1key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='header1value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='header2key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='header2value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params10key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params10value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params1key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params1value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params2key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params2value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params3key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params3value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params4key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params4value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params5key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params5value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params6key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params6value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params7key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params7value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params8key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params8value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params9key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='params9value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='endpoint',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
