# Generated by Django 3.1.6 on 2021-07-22 17:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0008_auto_20210722_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicall',
            options={'ordering': ['apiendpoint']},
        ),
        migrations.AlterField(
            model_name='apicall',
            name='datapoint',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('year_built', 'year_built'), ('home_size', 'home_size'), ('property_size', 'property_size'), ('bedrooms', 'bedrooms'), ('bathrooms', 'bathrooms'), ('zestimate_amount', 'zestimate_amount')], max_length=70),
        ),
    ]
