# Generated by Django 3.1.6 on 2021-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0009_auto_20210722_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apistore',
            name='apikeylocation',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='keyname',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='property',
            name='homesize',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='property',
            name='lotsize',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='property',
            name='yearbuilt',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='name',
            field=models.CharField(choices=[('Zillow GetDeepSearch', 'Zillow GetDeepSearch'), ('Bridge Zestimate', 'Bridge Zestimate'), ('Bridge Public Assessment', 'Bridge Public Assessment'), ('Great Schools', 'Great Schools'), ('FEMA Natural Disastors', 'Femal Natural Disastors')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ApiCall',
        ),
    ]
