# Generated by Django 3.1.6 on 2021-07-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0012_auto_20210722_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistore',
            name='bathrooms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='bedrooms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='homesize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='lotsize',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='yearbuilt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='zestimate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
