# Generated by Django 3.1.6 on 2021-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0013_auto_20210722_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apistore',
            old_name='endpoint',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='address',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='city',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='homesize',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='lotsize',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='state',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='yearbuilt',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='zestimate',
        ),
        migrations.RemoveField(
            model_name='apistore',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='last_sold_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='last_sold_price',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='property',
            name='rentzestimate',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='rentzestimate_high',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='rentzestimate_last_updated',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='rentzestimate_low',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='use_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='zestimate_high',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='zestimate_last_updated',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='zestimate_low',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='zillow_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='zillow_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
