# Generated by Django 3.1.6 on 2021-07-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0014_auto_20210723_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='name',
            field=models.CharField(choices=[('Zillow GetDeepSearch', 'Zillow GetDeepSearch'), ('Bridge Zestimate', 'Bridge Zestimate'), ('Bridge Public Assessment', 'Bridge Public Assessment'), ('Great Schools', 'Great Schools'), ('FEMA Natural Disastors', 'Femal Natural Disastors'), ('Google Maps', 'Google Maps')], max_length=50, null=True),
        ),
    ]
