# Generated by Django 3.1.6 on 2021-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0015_auto_20210723_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
