# Generated by Django 3.1.6 on 2021-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0016_auto_20210723_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sales_price',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
