# Generated by Django 3.1.6 on 2021-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0017_property_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='appraise_yr1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='appraise_yr2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='appraise_yr3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='appraise_yr4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='appraise_yr5',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_yr1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_yr2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_yr3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_yr4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_yr5',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='yr1',
            field=models.IntegerField(blank=True, default=2003),
        ),
        migrations.AddField(
            model_name='property',
            name='yr2',
            field=models.IntegerField(blank=True, default=2002),
        ),
        migrations.AddField(
            model_name='property',
            name='yr3',
            field=models.IntegerField(blank=True, default=2001),
        ),
        migrations.AddField(
            model_name='property',
            name='yr4',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='property',
            name='yr5',
            field=models.IntegerField(blank=True, default=1999),
        ),
    ]
