# Generated by Django 3.1.6 on 2021-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0018_auto_20210723_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='appraise_yr0',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_yr0',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
