# Generated by Django 3.1.6 on 2021-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0019_auto_20210724_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='appraise_rate',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
