# Generated by Django 3.1.6 on 2021-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0020_property_appraise_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tax_rate',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
