# Generated by Django 3.1.6 on 2021-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0022_auto_20210724_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='appraise_rate',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_rate',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
