# Generated by Django 3.1.6 on 2021-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0024_auto_20210724_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='downpayment',
            field=models.IntegerField(blank=True, default='20', max_length=3),
        ),
    ]
