# Generated by Django 3.1.6 on 2021-07-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0026_auto_20210724_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='downpayment',
            field=models.IntegerField(blank=True, default='20'),
        ),
    ]
