# Generated by Django 3.1.6 on 2021-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0028_auto_20210724_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='occupancy_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
