# Generated by Django 3.1.6 on 2021-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0029_auto_20210724_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='fema_yr1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='fema_yr2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='fema_yr3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='fema_yr4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='fema_yr5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='occupancy_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
