# Generated by Django 3.1.6 on 2021-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0030_auto_20210724_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='fema_yr1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='fema_yr2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='fema_yr3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='fema_yr4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='fema_yr5',
        ),
        migrations.AddField(
            model_name='property',
            name='fema1',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='fema2',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='fema3',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='fema4',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='fema5',
            field=models.CharField(blank=True, default='Unknown', max_length=200),
        ),
    ]
