# Generated by Django 3.1.6 on 2021-07-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0033_auto_20210724_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
