# Generated by Django 3.1.6 on 2021-07-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0034_auto_20210724_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_growth',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
