# Generated by Django 3.1.6 on 2021-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0035_auto_20210726_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='estimatedrent',
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_growth',
            field=models.CharField(blank=True, default='3.0', max_length=15),
        ),
    ]
