# Generated by Django 3.1.6 on 2021-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0036_auto_20210726_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gs_name_e',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='gs_name_h',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='gs_name_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='gs_rating_e',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='gs_rating_h',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='property',
            name='gs_rating_m',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
