# Generated by Django 3.1.6 on 2021-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0037_auto_20210727_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='capexrate',
            field=models.CharField(blank=True, default='4.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='apistore',
            name='name',
            field=models.CharField(choices=[('Zillow GetDeepSearch', 'Zillow GetDeepSearch'), ('Bridge Zestimate', 'Bridge Zestimate'), ('Bridge Public Assessment', 'Bridge Public Assessment'), ('Great Schools', 'Great Schools'), ('FEMA Natural Disastors', 'Femal Natural Disastors'), ('Google Maps', 'Google Maps'), ('US Census Bureau 2019', 'US Census Bureau 2019')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='leaserate',
            field=models.CharField(blank=True, default='8.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='pmrate',
            field=models.CharField(blank=True, default='8.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacancyrate',
            field=models.FloatField(blank=True, default='7.0'),
        ),
    ]
