# Generated by Django 3.1.6 on 2021-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0038_auto_20210729_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='capexfees',
        ),
        migrations.RemoveField(
            model_name='property',
            name='repairfees',
        ),
        migrations.AddField(
            model_name='property',
            name='pmfee',
            field=models.CharField(blank=True, default='8.0', max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='repairrate',
            field=models.FloatField(blank=True, default='8.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='capexrate',
            field=models.FloatField(blank=True, default='4.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='leaserate',
            field=models.FloatField(blank=True, default='8.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='pmrate',
            field=models.FloatField(blank=True, default='8.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_growth',
            field=models.FloatField(blank=True, default='3.0', max_length=15),
        ),
    ]
