# Generated by Django 3.1.6 on 2021-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0039_auto_20210729_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pmfee',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
