# Generated by Django 3.1.6 on 2021-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0040_auto_20210729_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='leaserate',
            field=models.FloatField(blank=True, default='3.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_growth',
            field=models.FloatField(blank=True, default='2.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='repairrate',
            field=models.FloatField(blank=True, default='3.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='vacancyrate',
            field=models.FloatField(blank=True, default='6.5'),
        ),
    ]
