# Generated by Django 3.1.6 on 2021-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0041_auto_20210730_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='appraise_rate',
            field=models.CharField(blank=True, default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_rate',
            field=models.CharField(blank=True, default='2', max_length=20),
        ),
    ]
