# Generated by Django 3.1.6 on 2021-07-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0042_auto_20210730_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['sitename'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='capexrate',
            field=models.FloatField(blank=True, default='3.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='otherfees',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='repairrate',
            field=models.FloatField(blank=True, default='5.0', max_length=15),
        ),
    ]
