# Generated by Django 3.1.6 on 2021-07-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0043_auto_20210730_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='images'),
        ),
    ]
