# Generated by Django 3.1.6 on 2021-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blakerussell', '0046_auto_20210804_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='appraise_yr0',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='appraise_yr1',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='appraise_yr2',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='appraise_yr3',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='appraise_yr4',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='appraise_yr5',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_yr0',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_yr1',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_yr2',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_yr3',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_yr4',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_yr5',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
    ]
